### ISSUE TITLE
App can not be started on macOs

### ISSUE THREAD

**Issue by BeyerMart** [skymatic/appstore-reverse-charger#11]
The app can not be run on macOS. This is the error message:
`Error: Could not find or load main class Support.AppStoreReverseCharger.settings.json
Caused by: java.lang.ClassNotFoundException: Support.AppStoreReverseCharger.settings.json`

Somehow the app looks for the class settings.json which is not a class.

@overheadhunter suggested replacing 
`-DsettingsPath="~/Library/Application Support/AppStoreReverseCharger/settings.json"`
with 
`-DsettingsPath=~/Library/Application\ Support/AppStoreReverseCharger/settings.json`

**Comment by tobihagemann** [comment]
Fixed in f920e40e930ce55b18514c6a5b81498fb5f55347
